apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.11.0
    helm:
      releaseName: cncf-gha-controller
      valueFiles:
        - $values/ci/cluster/oci/arc/values.yaml
  - ref: values
    repoURL: https://github.com/cncf/automation.git
    targetRevision: main
