apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-8cpu-32gb-x86-64
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: argocd-notifications
  labels:
    cluster: oci-gha-amd64-runners
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    path: ci/cluster/oci/runners/8cpu-32gb/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
