---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cncf-arc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/oci-arm64/arc/
      targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/oci-arm64/runners/
      targetRevision: HEAD
      directory:
        recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/oci-arm64/monitoring/
      targetRevision: HEAD
      directory:
        recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/oci-arm64/external-secrets/
      targetRevision: HEAD
      directory:
        recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hacks
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  syncPolicy:
    automated: {}
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/oci-arm64/hacks/
      targetRevision: HEAD
      directory:
        recurse: true
---
