apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-secret-store
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.us-sanjose-1.grt7sucpaae7c.abzwuljr6iq3nf347j2g3gow4iai2gbqtwlwzujsbma46wb6dz7nnteoh6kq
      region: us-sanjose-1
      principalType: UserPrincipal
      auth:
        user: ocid1.user.oc1..aaaaaaaaiwfw4ip3eggqbv7ds5c65d4qc25sya6lqne6ar7ge2ipfj4p2peq
        tenancy: ocid1.tenancy.oc1..aaaaaaaalnpeq6xok4okj5vknc2pzancima3g5bwvk3kk2jgwhgycacrie3q
        secretRef:
          privatekey:
            name: oracle-secret
            key: privateKey
            namespace: external-secrets
          fingerprint:
            name: oracle-secret
            key: fingerprint
            namespace: external-secrets
