apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codimd-auth-env
  namespace: codimd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: codimd-auth-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: codimd-auth-env
