apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oidc-client-credentials
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: github-oidc-client-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: github-oidc-client-credentials
