apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kcp-kubeconfig
  namespace: kdp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: cluster-admin-kubeconfig
    creationPolicy: Owner
    template:
      data:
        kubeconfig: "{{ .kubeconfig | toString }}"
  data:
  - secretKey: kubeconfig
    remoteRef:
      key: kcp-kubeconfig
