apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-client-secret
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: oidc-client-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: oidc-client-secret
