apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
        - "actions.github.com"
      kinds:
        - AutoscalingListener
      clusters:
        - "*"
