apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-amd64-runners
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.4.2
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - $values/ci/cluster/oci/monitoring/values.yaml
  - repoURL: https://github.com/cncf/automation.git
    targetRevision: HEAD
    ref: values
