apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: cncf-gha-controller
      valueFiles:
        - values.yaml
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
