apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-vm-24cpu-384gb-arm64
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-amd64-runners
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    path: ci/cluster/oci/vm-runners/24cpu-384gb-arm64/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
