apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "05"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  source:
    repoURL: https://charts.dexidp.io
    targetRevision: 0.23.0
    chart: dex
    helm:
      values: |
        replicaCount: 2
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: auth.services.cncf.io
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: auth-dex-tls
              hosts:
                - auth.services.cncf.io
        envVars:
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-client-secret
              key: oidc-client-secret
        envFrom:
        - secretRef:
            name: github-oidc-client-credentials
        config:
          issuer: "https://auth.services.cncf.io/dex"
          oauth2:
            skipApprovalScreen: true
            responseTypes:
              - code
              - token
              - id_token
          storage:
            type: kubernetes
            config:
              inCluster: true
          expiry:
            idTokens: 24h
            signingKeys: 6h
          staticClients:
            - id: kdp-kubelogin
              name: kdp-kubelogin
              secretEnv: OIDC_CLIENT_SECRET
              RedirectURIs:
              - http://localhost:8000
              - http://localhost:18000
              - http://localhost:3000/api/auth/callback/dex
              - https://services.cncf.io/oauth/callback
              - https://services.cncf.io/api/auth/callback/oidc
          connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $GITHUB_CLIENT_ID
              clientSecret: $GITHUB_CLIENT_SECRET
              redirectURI: https://auth.services.cncf.io/dex/callback
              orgs:
                - name: cncf
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
