apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp-exporter
rules:
  - apiGroups: ["apis.kcp.io"]
    resources: ["apiexports"]
    verbs: ["get"]
  - apiGroups: ["apis.kcp.io"]
    resources: ["apiexports/content"]
    resourceNames: ["tenancy.kcp.io"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apis.kcp.io"]
    resources: ["apiexports/content"]
    resourceNames: ["core.kdp.k8c.io"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdp-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp-exporter
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kdp-exporter
