#                Kubermatic Enterprise Read-Only License
#                       Version 1.0 ("KERO-1.0")
#                   Copyright © 2024 Kubermatic GmbH
#
# 1.	You may only view, read and display for studying purposes the source
#    code of the software licensed under this license, and, to the extent
#    explicitly provided under this license, the binary code.
# 2.	Any use of the software which exceeds the foregoing right, including,
#    without limitation, its execution, compilation, copying, modification
#    and distribution, is expressly prohibited.
# 3.	THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# END OF TERMS AND CONDITIONS
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:service-viewers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:services:viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:dbms.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - dbms.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:pki.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - pki.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:scm.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - scm.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:dbms.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:dbms.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:pki.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:pki.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:scm.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:scm.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
