---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:service-viewers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:services:viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:dbms.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - dbms.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:pki.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - pki.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdp:service:scm.example.corp:use
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apiexports
  resourceNames:
  - scm.example.corp
  verbs:
  - bind
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:dbms.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:dbms.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:pki.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:pki.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermatic:scm.example.corp:use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdp:service:scm.example.corp:use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:kubermatic:internal
---
