apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/equinix/arc/
      targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: equinix-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/equinix/autoscaler/
      targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: github-arc
  sources:
    - repoURL: https://github.com/cncf/automation.git
      path: ci/cluster/equinix/runners/
      targetRevision: HEAD
      directory:
        recurse: true
