apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-32cpu-128gb-arm64
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    path: ci/cluster/oci-arm64/runners/32cpu-128gb/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
