apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: equinix-4cpu-16gb
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      releaseName: equinix-4cpu-16gb
      valueFiles:
      - $values/ci/cluster/equinix/runners/4cpu-16gb/values.yaml
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: equinix-4cpu-16gb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true