name: Test all Oracle Runners

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cncf_ora_rnrs_matrix:
    strategy:
      matrix:
        cncf_runner: [oracle-16cpu-64gb-x86-64, oracle-16cpu-64gb-arm64, oracle-4cpu-16gb-x86-64, oracle-8cpu-32gb-x86-64, oracle-24cpu-384gb-x86-64, oracle-2cpu-8gb-arm64, oracle-32cpu-128gb-arm64]

    runs-on: ${{ matrix.cncf_runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run uname to verify architecture
        run: uname -a

      - name: Run a basic workload
        run: |
          echo "Testing Oracle runner ${{matrix.cncf_runner}}"
          echo "CPU Info:"
          lscpu

      - name: Run a Docker container
        run: |
          docker run --rm alpine echo "Docker is working on ${{matrix.cncf_runner}}"

      - name: Check local disk
        run: |
         echo "df -h on ${{matrix.cncf_runner}}"
         df -h /
